project_id = "agiazdqztkagivnenomq"

[functions.generate-subtitles]
verify_jwt = false

[functions.transloadit-process]
verify_jwt = false

[functions.mercadopago-checkout]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false
