project_id = "agiazdqztkagivnenomq"

[functions.generate-subtitles]
verify_jwt = false

[functions.transloadit-process]
verify_jwt = false

[functions.mercadopago-checkout]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.upload-testimonial]
verify_jwt = false

[functions.chat-roteiros]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.instagram-auth]
verify_jwt = false

[functions.instagram-publish]
verify_jwt = false
